# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38c1f59394d4452816d5ecb3747036df117a60bd97eaab8a6cf119a56c9497bb4b5c74c16061f6c83816dc1c94b882dadee442fceee1cbd5c6353c973c150eed
  aws_access_key: AKIAI2E3INNQULCCGHQQ
  aws_secret_key: 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
  aws_bucket: hcd-bucket
  aws_region: us-east-1
test:
  secret_key_base: 4479e13a54fe999c858ecbbb58d6b868f020cb253f02e5ff66459b104bf31202691c5ce6109eb0ec39fcca6fc6f3db4dfdf728013ec235c5e7590ba3cb75f8d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 38c1f59394d4452816d5ecb3747036df117a60bd97eaab8a6cf119a56c9497bb4b5c74c16061f6c83816dc1c94b882dadee442fceee1cbd5c6353c973c150eed
  aws_access_key: AKIAI2E3INNQULCCGHQQ
  aws_secret_key: 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
  aws_bucket: hcd-bucket
  aws_region: us-east-1